version: '3.4'

services:
  catalogdb:
    image: mongo

  redisdb:
    image: redis:alpine 

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket/WebApplication1/Dockerfile

volumes:
  mongo_data: