version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

    redisdb:
        container_name: redisdb
        restart: always
        ports:
            - "6379:6379"
          
    catalog.api:
        container_name: catalog.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
            - catalogdb
        ports:
            - "8000:80"    

    basket.api:
        container_name: basket.api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=redisdb:6379"
        depends_on:
            - redisdb
        ports:
            - "8001:80" 